Repository DevDanielNAM/BFC, pull requests merged in 2024-06, with the labels that each got.

#9 Refactor/#8 addreply editreply 코드 수정
  src/main/webapp/board/addReply.jsp
  src/main/webapp/board/editReply.jsp
Labels: refactor

#12 Feture/#4 글 작성 페이지
  src/main/java/com/bfc/board/PostDAO.java
  src/main/java/com/bfc/board/SimplePostDTO.java
  src/main/java/com/bfc/member/UserDAO.java
  src/main/java/com/bfc/member/UserDTO.java
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/upload.jsp
  src/main/webapp/main/main.jsp
  src/main/webapp/member/UserUpload.jsp
  src/main/webapp/member/mypage.jsp
  src/main/webapp/member/userEdit.jsp
  src/main/webapp/member/userInformation.jsp
  src/main/webapp/resources/css/boardEdit.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/userEdit.css
  src/main/webapp/resources/js/boardEdit.js
  src/main/webapp/resources/js/mypage.js
  src/main/webapp/resources/js/userEdit.js
Labels: refactor, 종경

#13 Feature/#10 캐러셀 슬라이드 구현
  .classpath
  build/classes/com/bfc/board/.gitkeep
  build/classes/com/bfc/member/.gitkeep
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/resources/css/boardDetail.css
  src/main/webapp/resources/images/next_button.png
  src/main/webapp/resources/images/prev_button.png
  src/main/webapp/resources/js/boardDetail.js
Labels: feature, 기성

#15 #14 DTO 추가
  src/main/java/com/bfc/board/ContentDTO.java
  src/main/java/com/bfc/board/PostDAO.java
  src/main/java/com/bfc/board/PostDTO.java
Labels: feature, 종경

#19 Modify/#18 mysql db 변경
  src/main/java/com/bfc/board/ReplyDAO.java
  src/main/webapp/board/boardDetail.jsp
Labels: modify, 기성

#23 Fix/#22 게시글 코스 여러 개일 경우 태그등록 안 되는 버그 수정
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/update.jsp
  src/main/webapp/board/upload.jsp
  src/main/webapp/resources/js/boardEdit.js
Labels: fix, 기성

#24 Feature/#16 메인페이지
  .classpath
  src/main/java/com/bfc/board/HashtagDTO.java
  src/main/java/com/bfc/board/PostDAO.java
  src/main/java/com/bfc/board/ReplyDAO.java
  src/main/java/com/bfc/member/UserDAO.java
  src/main/webapp/board/upload.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/main/main.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/js/boardEdit.js
Labels: feature, 성현

#25 Modify/#21 상세페이지 db 값으로 화면 그리기
  src/main/java/com/bfc/board/PostDAO.java
  src/main/java/com/bfc/board/ReplyDAO.java
  src/main/java/com/bfc/member/UserDAO.java
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/board/boardEditDeleteRedirect.jsp
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/board/update.jsp
  src/main/webapp/board/upload.jsp
  src/main/webapp/resources/js/boardDetail.js
  src/main/webapp/resources/js/boardEdit.js
Labels: refactor, feature, modify, fix, 기성

#27 Chore/#26 오타수정 gitkeep 삭제
  src/main/java/com/bfc/board/.gitkeep
  src/main/java/com/bfc/member/.gitkeep
  src/main/webapp/board/.gitkeep
  src/main/webapp/board/boardEditDeleteRedirect.jsp
  src/main/webapp/main/.gitkeep
  src/main/webapp/member/.gitkeep
  src/main/webapp/resources/css/.gitkeep
  src/main/webapp/resources/images/.gitkeep
  src/main/webapp/resources/js/.gitkeep
  src/main/webapp/uploadImages/.gitkeep
Labels: chore, 기성

#29 Feature/#28 메인페이지
  .classpath
  build/classes/.gitignore
  build/classes/com/bfc/board/.gitkeep
  build/classes/com/bfc/member/.gitkeep
  src/main/java/com/bfc/board/PostDAO.java
  src/main/java/com/bfc/member/UserDAO.java
  src/main/webapp/main/main.jsp
  src/main/webapp/member/login.jsp
  src/main/webapp/member/signup.jsp
  src/main/webapp/member/signupProcess.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/login.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/css/signup.css
  src/main/webapp/resources/js/main.js
Labels: feature, 성현

#33 #32 수정 페이지 + 버튼 추가
  src/main/java/com/bfc/board/PostDAO.java
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/board/update.jsp
  src/main/webapp/resources/js/boardUpdate.js
  src/main/webapp/resources/js/mypage.js
Labels: feature, 종경

#34 feature : 로그인
  src/main/java/com/bfc/member/UserDAO.java
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/board/update.jsp
  src/main/webapp/board/upload.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/main/main.jsp
  src/main/webapp/member/UserUpload.jsp
  src/main/webapp/member/login.jsp
  src/main/webapp/member/loginProcess.jsp
  src/main/webapp/member/logout.jsp
  src/main/webapp/member/mypage.jsp
  src/main/webapp/member/signupProcess.jsp
  src/main/webapp/member/userEdit.jsp
  src/main/webapp/resources/css/header.css
Labels: feature, 성현

#36 Modify/#35 로그인 여부에 따른 권한 설정
  src/main/java/com/bfc/board/ReplyDAO.java
  src/main/java/com/bfc/board/ReplyDTO.java
  src/main/webapp/board/addReply.jsp
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/board/replyList.jsp
  src/main/webapp/resources/js/boardDetail.js
Labels: modify, 기성

#38 [fix] #37: 게시글 작성자만 삭제
  src/main/webapp/board/boardDetail.jsp
Labels: fix, 기성

#40 [feature] #39: 코스 이미지 클릭 시 상세 페이지 화면에 그리기
  .classpath
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/board/getHashtags.jsp
  src/main/webapp/resources/css/boardDetail.css
  src/main/webapp/resources/js/boardDetail.js
Labels: feature, 기성

#42 [fix] #41: 상세페이지 세션 로그인 확인 버그 수정
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/resources/js/boardDetail.js
Labels: fix, 기성

#45 [fix] #43: 상세페이지 댓글 수정, 삭제 시 발생하는 오류 수정
  src/main/webapp/board/deleteReply.jsp
  src/main/webapp/board/editReply.jsp
  src/main/webapp/board/replyList.jsp
Labels: fix, 기성

#47 #44 사진 업로드 시 이미지 3개
  src/main/java/com/bfc/board/ContentDTO.java
  src/main/java/com/bfc/board/ImageDTO.java
  src/main/java/com/bfc/board/PostDAO.java
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/board/update.jsp
  src/main/webapp/board/upload.jsp
  src/main/webapp/resources/css/boardEdit.css
  src/main/webapp/resources/js/boardEdit.js
  src/main/webapp/resources/js/boardUpdate.js
Labels: feature, 종경

#48 [modify] #46: 상세페이지 코스 선택 시 보여지는 화면 수정
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/resources/css/boardDetail.css
  src/main/webapp/resources/js/boardDetail.js
Labels: modify, 기성

#52 Refactor/#49 image테이블 생성에 따른 코드 수정
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/resources/css/boardDetail.css
  src/main/webapp/resources/js/boardDetail.js
Labels: refactor, 기성

#51 refactor : index.jsp로 메인페이지설정
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/boardEditDeleteRedirect.jsp
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/board/update.jsp
  src/main/webapp/board/upload.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/index.jsp
  src/main/webapp/main/main.jsp
  src/main/webapp/member/loginProcess.jsp
  src/main/webapp/member/logout.jsp
  src/main/webapp/member/userInformation.jsp
  src/main/webapp/resources/js/main.js
Labels: refactor, 성현

#54 [refactor] #53: 메인페이지 주소 수정
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/resources/js/boardDetail.js
Labels: refactor, 기성

#56 [refactor] #55: 회원가입, 회원정보 자바빈즈 액션태그로 수정
  src/main/webapp/member/UserUpload.jsp
  src/main/webapp/member/signupProcess.jsp
Labels: refactor, 기성

#58 [modify] #57: 로그인, 로그아웃 리다이렉트 수정
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/common/footer.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/index.jsp
  src/main/webapp/main/main.jsp
  src/main/webapp/member/login.jsp
  src/main/webapp/member/loginProcess.jsp
  src/main/webapp/member/logout.jsp
  src/main/webapp/member/mypage.jsp
  src/main/webapp/member/signup.jsp
  src/main/webapp/member/userEdit.jsp
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/js/boardDetail.js
Labels: modify, 기성

#60 Design/#59 header footer UI 변경
  src/main/webapp/common/footer.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/resources/css/boardDetail.css
  src/main/webapp/resources/css/footer.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/login.css
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/signup.css
  src/main/webapp/resources/css/userEdit.css
  src/main/webapp/resources/images/header.png
Labels: 기성

#62 [design] #61: 로그인, 회원가입 ui변경
  src/main/webapp/member/login.jsp
  src/main/webapp/member/signup.jsp
  src/main/webapp/resources/css/login.css
  src/main/webapp/resources/css/signup.css
  src/main/webapp/resources/images/login_signup.jpeg
Labels: 기성, design

#65 #64-회원 탈퇴 로직 추가
  src/main/java/com/bfc/board/PostDAO.java
  src/main/java/com/bfc/member/UserDAO.java
  src/main/webapp/member/userInformation.jsp
Labels: feature, 종경

#66 Design/#63 마이페이지 UI 변경
  src/main/webapp/member/mypage.jsp
  src/main/webapp/member/userEdit.jsp
  src/main/webapp/resources/css/mypage.css
  src/main/webapp/resources/css/signup.css
  src/main/webapp/resources/css/userEdit.css
Labels: 기성, design

#68 Design/#67 여행지 등록 수정 UI 변경
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/board/boardUpdate.jsp
  src/main/webapp/resources/css/boardEdit.css
  src/main/webapp/resources/js/boardEdit.js
  src/main/webapp/resources/js/boardUpdate.js
Labels: 기성, design

#70 [design] #69: 상세페이지 ui변경
  src/main/webapp/resources/css/boardDetail.css
Labels: 기성, design

#72 [design] #71: 메인페이지 ui변경
  src/main/webapp/board/boardEdit.jsp
  src/main/webapp/common/header.jsp
  src/main/webapp/main/main.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/js/boardEdit.js
Labels: 기성, design

#74 [fix] : 검색
  .classpath
  src/main/java/com/bfc/board/PostDAO.java
  src/main/webapp/main/main.jsp
Labels: fix, 성현

#76 [fix] #75: 상세페이지 태그 쿼리스트링 수정
  src/main/webapp/board/boardDetail.jsp
  src/main/webapp/resources/js/boardDetail.js
Labels: fix, 기성

#78 [fix] #77: upload시 postId 폴더 생성 오류 수정
  src/main/webapp/board/upload.jsp
Labels: fix, 기성

#79 [fix] #77: upload시 postId 폴더 생성 오류 수정
  src/main/webapp/board/upload.jsp
Labels: fix, 기성

#81 Fix/#80 댓글 수정 오류
  src/main/webapp/board/replyList.jsp
  src/main/webapp/resources/css/main.css
  src/main/webapp/resources/css/mypage.css
Labels: fix, 기성, design
